let data=[];const $=s=>document.querySelector(s);const SUPABASE_URL="https://ymnawoeifbdnmxrsiaxa.supabase.co";const SUPABASE_PUBLISHABLE_KEY="sb_publishable_dkUGSA4UXU9GMbvMp5Z91w_CNcvmKw5";let summitAuth=null;let currentSession=null;let currentSubject=0;
function getAuthReturnUrl(){if(location.hostname.endsWith("github.io"))return `${location.origin}/sum-mit-sat-math/`;return `${location.origin}/`}
function initTheme(){const saved=localStorage.getItem("summit-theme")||"light";document.documentElement.dataset.theme=saved;$("#themeToggle")?.addEventListener("click",()=>{const n=document.documentElement.dataset.theme==="dark"?"light":"dark";document.documentElement.dataset.theme=n;localStorage.setItem("summit-theme",n)})}
function leafHTML(l){return `<div class="leaf"><div class="leaf-title">${l.title}</div><div class="leaf-actions"><a href="${l.base}/explanation/">Explanation</a><a href="${l.base}/problems/">Problems</a><a href="${l.base}/answers/">Answers</a><a href="${l.base}/video/arabic/">Video · عربي</a><a href="${l.base}/video/english/">Video · English</a><a href="${l.base}/test/">Test</a></div></div>`}
function groupHTML(g){return `<div class="group"><button class="group-toggle">${g.title}<span class="chev">⌄</span></button><div class="section-body">${g.leaves.map(leafHTML).join("")}</div></div>`}
function sectionHTML(s){return `<div class="tree-section"><button class="section-toggle">${s.title}<span><span style="font-weight:400;color:var(--muted);font-size:12px;margin-right:12px">${s.leaves.length+s.groups.reduce((a,g)=>a+g.leaves.length,0)} lessons</span><span class="chev">⌄</span></span></button><div class="section-body">${s.leaves.map(leafHTML).join("")}${s.groups.map(groupHTML).join("")}</div></div>`}
function subjectLeaves(s){const out=[];for(const sec of s.sections||[]){for(const l of sec.leaves||[])out.push({leaf:l,section:sec.title});for(const g of sec.groups||[])for(const l of g.leaves||[])out.push({leaf:l,section:g.title||sec.title})}return out}
function sampleHTML(s){const items=subjectLeaves(s).slice(0,3);return `<div class="sample-wrap"><div class="sample-head"><span>FREE PREVIEW</span><p>A quick look at how SUMMIT lessons are structured. Sign in to open the full curriculum.</p></div><div class="sample-list">${items.map((x,i)=>`<article class="sample-lesson"><div class="sample-number">0${i+1}</div><div class="sample-copy"><small>${x.section}</small><h3>${x.leaf.title}</h3><div class="sample-actions"><a href="${x.leaf.base}/explanation/">Preview explanation</a><button type="button" data-auth-open="signup">Unlock full lesson</button></div></div></article>`).join("")}</div><div class="sample-gate"><div><b>Ready for the full SAT Math path?</b><span>298 focused lessons with practice, answers, tests and video routes.</span></div><button type="button" data-auth-open="signup">Create free account</button></div></div>`}
function renderSubject(i){currentSubject=i;document.querySelectorAll(".subject-btn").forEach((b,j)=>b.classList.toggle("active",j===i));const s=data[i];if(!s)return;$("#treeTitle").textContent=s.title;const total=subjectLeaves(s).length;$("#lessonCount").textContent=currentSession?`${total} leaf lessons · ${total*6} routes`:`3 lesson examples`;if(currentSession){$("#tree").innerHTML=s.sections.map(sectionHTML).join("");$("#tree .tree-section")?.classList.add("open");$("#tree .group")?.classList.add("open");bindTree()}else{$("#tree").innerHTML=sampleHTML(s);bindAuthOpeners()}}
function bindTree(){document.querySelectorAll(".section-toggle,.group-toggle").forEach(b=>b.onclick=()=>b.parentElement.classList.toggle("open"))}
function setMessage(id,message,type=""){const el=$(id);if(!el)return;el.textContent=message||"";el.className=`auth-message${type?` ${type}`:""}`}
function setAuthBusy(form,busy,text){if(!form)return;const btn=form.querySelector(".auth-submit");if(!btn)return;if(!btn.dataset.label)btn.dataset.label=btn.textContent;btn.disabled=busy;btn.textContent=busy?text:btn.dataset.label}
function switchAuth(mode){const signup=mode==="signup";$("#signinForm").hidden=signup;$("#signupForm").hidden=!signup;document.querySelectorAll("[data-auth-tab]").forEach(b=>b.classList.toggle("active",b.dataset.authTab===mode));$("#authTitle").textContent=signup?"Create your SUMMIT account.":"Welcome back.";$("#authSubtitle").textContent=signup?"Save your place and unlock the complete SAT Math curriculum.":"Sign in and continue exactly where you left off.";setMessage("#signinMessage","");setMessage("#signupMessage","")}
function openAuth(mode="signin"){switchAuth(mode);const modal=$("#authModal");modal.classList.add("open");modal.setAttribute("aria-hidden","false");document.body.classList.add("auth-open");setTimeout(()=>$(mode==="signup"?"#signupName":"#signinEmail")?.focus(),80)}
function closeAuth(){const modal=$("#authModal");modal?.classList.remove("open");modal?.setAttribute("aria-hidden","true");document.body.classList.remove("auth-open")}
async function loadProfile(user){if(!summitAuth||!user)return null;const {data:profile}=await summitAuth.from("profiles").select("full_name,username").eq("id",user.id).maybeSingle();return profile}
async function renderAuthState(session){currentSession=session||null;const wrap=$("#authLinks");if(wrap){if(!session?.user){wrap.innerHTML='<button class="auth-link" type="button" data-auth-open="signin">Sign in</button><button class="auth-link primary" type="button" data-auth-open="signup">Sign up</button>';bindAuthOpeners()}else{const profile=await loadProfile(session.user);const meta=session.user.user_metadata||{};const name=profile?.full_name||meta.full_name||session.user.email?.split("@")[0]||"Student";const username=profile?.username||meta.username||"student";const initials=name.trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||"").join("")||"S";wrap.innerHTML=`<div class="user-menu"><button class="user-pill" type="button" id="userMenuButton"><span class="user-avatar">${initials}</span><span class="user-copy"><strong>${name}</strong><small>@${username}</small></span><span class="user-chevron">⌄</span></button><div class="user-dropdown" id="userDropdown"><div><b>${name}</b><span>${session.user.email}</span></div><button type="button" id="signOutButton">Sign out</button></div></div>`;$("#userMenuButton")?.addEventListener("click",e=>{e.stopPropagation();$("#userDropdown")?.classList.toggle("open")});$("#signOutButton")?.addEventListener("click",async()=>{await summitAuth.auth.signOut({scope:"local"});$("#userDropdown")?.classList.remove("open")})}}if(data.length)renderSubject(currentSubject)}
function bindAuthOpeners(){document.querySelectorAll("[data-auth-open]").forEach(b=>b.onclick=()=>openAuth(b.dataset.authOpen||"signin"))}
function friendlyAuthError(error){const m=(error?.message||"Something went wrong. Please try again.").toLowerCase();if(m.includes("user already registered"))return "An account already exists with this email. Sign in instead.";if(m.includes("invalid login credentials"))return "Email or password is incorrect.";if(m.includes("duplicate")||m.includes("username")||m.includes("database error saving new user"))return "That username may already be taken. Try another one.";if(m.includes("password"))return error.message;return error?.message||"Something went wrong. Please try again."}
function initAuthUI(){if(!window.supabase?.createClient)return;summitAuth=window.supabase.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);bindAuthOpeners();document.querySelectorAll("[data-auth-close]").forEach(b=>b.onclick=closeAuth);document.querySelectorAll("[data-auth-tab]").forEach(b=>b.onclick=()=>switchAuth(b.dataset.authTab));document.querySelectorAll("[data-password-toggle]").forEach(b=>b.onclick=()=>{const input=$("#"+b.dataset.passwordToggle);if(!input)return;const show=input.type==="password";input.type=show?"text":"password";b.textContent=show?"Hide":"Show"});document.addEventListener("keydown",e=>{if(e.key==="Escape")closeAuth()});document.addEventListener("click",e=>{if(!e.target.closest(".user-menu"))$("#userDropdown")?.classList.remove("open")});
$("#signinForm")?.addEventListener("submit",async e=>{e.preventDefault();setMessage("#signinMessage","");const email=$("#signinEmail").value.trim();const password=$("#signinPassword").value;setAuthBusy(e.currentTarget,true,"Signing in…");const {data:res,error}=await summitAuth.auth.signInWithPassword({email,password});setAuthBusy(e.currentTarget,false);if(error){setMessage("#signinMessage",friendlyAuthError(error),"error");return}if(res.session){setMessage("#signinMessage","Signed in. Welcome back.","success");setTimeout(closeAuth,350)}});
$("#signupForm")?.addEventListener("submit",async e=>{e.preventDefault();setMessage("#signupMessage","");const full_name=$("#signupName").value.trim();const username=$("#signupUsername").value.trim().toLowerCase();const email=$("#signupEmail").value.trim();const password=$("#signupPassword").value;if(full_name.length<2){setMessage("#signupMessage","Enter your full name.","error");return}if(!/^[a-z0-9_]{3,24}$/.test(username)){setMessage("#signupMessage","Username must be 3–24 characters using letters, numbers, or _ only.","error");return}if(password.length<8){setMessage("#signupMessage","Password must be at least 8 characters.","error");return}setAuthBusy(e.currentTarget,true,"Creating your account…");const {data:res,error}=await summitAuth.auth.signUp({email,password,options:{emailRedirectTo:getAuthReturnUrl(),data:{full_name,username}}});setAuthBusy(e.currentTarget,false);if(error){setMessage("#signupMessage",friendlyAuthError(error),"error");return}if(res.session){setMessage("#signupMessage","Account created. You're in!","success");e.currentTarget.reset();setTimeout(closeAuth,450)}else{setMessage("#signupMessage","Account created. Check your email to confirm it, then you'll return to SUMMIT.","success")}});
summitAuth.auth.getSession().then(({data:{session}})=>{renderAuthState(session);if(session&&location.hash&&(location.hash.includes("access_token")||location.hash.includes("refresh_token")))history.replaceState({},document.title,getAuthReturnUrl())});summitAuth.auth.onAuthStateChange((_event,session)=>setTimeout(()=>renderAuthState(session),0))}
async function init(){initTheme();initAuthUI();try{data=await fetch("/curriculum.json").then(r=>{if(!r.ok)throw new Error("Curriculum failed to load");return r.json()});const icons=["x²","Σ","%","△"];$("#subjectList").innerHTML=data.map((s,i)=>`<button class="subject-btn"><span class="subject-icon">${icons[i]}</span><span class="subject-name"><small>0${i+1}</small>${s.title}</span><span>›</span></button>`).join("");document.querySelectorAll(".subject-btn").forEach((b,i)=>b.onclick=()=>renderSubject(i));renderSubject(0)}catch(e){console.error(e)}}document.addEventListener("DOMContentLoaded",init);
