(function shellModule(){
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const base='problem-solving-and-data-analysis/rates/unit-rates';
const nav=['explanation','problems','answers','test','video/english','video/arabic'].map(x=>'<a href="/'+base+'/'+x+'/">'+x+'</a>').join(' · ');
const css='<style>.lesson-section{padding:1.2rem;margin:1rem 0;border:1px solid #cbd6e4;border-radius:14px}.section-kicker{font-weight:700;color:#53708b}.summit-q{padding:1rem;border-bottom:1px solid #d8e1ea}.summit-options{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.5rem}.summit-options button,.summit-action{padding:.7rem;border:1px solid #8299b2;border-radius:9px;background:transparent;color:inherit;cursor:pointer}.summit-options button[aria-pressed=true]{background:#174c7b;color:white}.summit-feedback{min-height:1.5em}.summit-video-scene{background:#112b49;color:white;aspect-ratio:16/9;display:flex;flex-direction:column;justify-content:center;align-items:center;text-align:center;padding:2rem;border-radius:16px}.summit-video-scene h2{color:#ffe3a6}.summit-controls{display:flex;flex-wrap:wrap;gap:.5rem;margin-top:1rem}.summit-nav{display:flex;flex-wrap:wrap;gap:1rem;margin:2rem 0}@media(max-width:650px){.summit-options{grid-template-columns:1fr}}</style>';
function shell(kind,body,script='',lang='en'){return '<!doctype html><html lang="'+lang+'"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><title>Unit Rates — '+e(kind)+' | SUMMIT SAT MATH</title>'+css+'</head><body><header class="topbar"><a class="brand" href="/">SUMMIT SAT MATH</a><nav><a href="/">Home</a><a href="/#subjects">Subjects</a></nav></header><main class="page-shell"><section class="lesson-card"><div class="crumb">Problem-Solving and Data Analysis · Rates</div><div class="page-type">'+e(kind)+'</div><h1 class="lesson-title">Unit Rates</h1><article class="lesson-content">'+body+'</article><nav class="summit-nav">'+nav+'</nav></section></main>'+script+'</body></html>'}
const section=(h,b,i)=>'<section class="lesson-section"><span class="section-kicker">'+(i==null?'':String(i+1).padStart(2,'0')+' · ')+e(h)+'</span><h2>'+e(h)+'</h2>'+b+'</section>';
const groups=[['SKILL CHECK',0,3],['CORE PRACTICE',3,11],['EXAM-STYLE PRACTICE',11,16],['CHALLENGE PROBLEMS',16,18]];
function card(q,i,k){const opts=[...q.options],shift=i%4;opts.splice(shift,0,opts.shift());return '<div class="summit-q" data-'+k+'="'+i+'" data-answer="'+shift+'"><h3>'+(i+1)+'. '+e(q.prompt)+'</h3><div class="summit-options">'+opts.map((o,j)=>'<button type="button" data-index="'+j+'" aria-pressed="false">'+e(o)+'</button>').join('')+'</div><p class="summit-feedback" aria-live="polite"></p></div>'}
module.exports={e,base,shell,section,groups,card};
})();
