const fs=require('fs');const path=require('path');const zlib=require('zlib');const root=__dirname;const dist=path.join(root,'dist');
const curriculumRaw=zlib.gunzipSync(Buffer.from(fs.readFileSync(path.join(root,'curriculum.json.gz.b64'),'utf8').trim(),'base64')).toString('utf8');const curriculum=JSON.parse(curriculumRaw);
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const header=`<header class="topbar"><a class="brand" href="/"><span class="brand-mark"></span><span class="brand-copy">SUMMIT<small>SAT MATH</small></span></a><nav><a href="/">Home</a><a href="/#subjects">Subjects</a><a href="/#subjects">Practice</a><a href="/#subjects">Progress</a></nav><div class="actions"><button class="lang">EN <span>|</span> عربي</button><button id="themeToggle" class="theme">◐</button></div></header>`;
const theme=`<script>(()=>{const s=localStorage.getItem('summit-theme')||'light';document.documentElement.dataset.theme=s;document.getElementById('themeToggle')?.addEventListener('click',()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('summit-theme',n)})})();</script>`;
const leaves=[];for(const subject of curriculum){for(const section of subject.sections||[]){for(const leaf of section.leaves||[])leaves.push({subject,section,group:null,leaf});for(const group of section.groups||[])for(const leaf of group.leaves||[])leaves.push({subject,section,group,leaf});}}
function genericTest(item){const{subject,section,group,leaf}=item;const crumb=[subject.title,section.title,group&&group.title].filter(Boolean).join(' · ');return `<!doctype html><html lang="en" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/styles.css"><title>${esc(leaf.title)} — Test | SUMMIT SAT MATH</title></head><body>${header}<main class="page-shell"><section class="coming-card"><div class="crumb">${esc(crumb)}</div><div class="page-type">LESSON TEST</div><div class="lesson-title">${esc(leaf.title)}</div><div class="subject-label">${esc(subject.title)}</div><div class="soon">5-QUESTION TEST</div><p class="video-note">This test is not part of the timed release queue. It will contain exactly five questions from Easy to Hard / SAT-style, and the full result will appear only after Submit Test.</p><a class="back" href="../explanation/">← Back to Explanation</a></section></main>${theme}</body></html>`}
for(const item of leaves){const route=item.leaf.base.replace(/^\//,'').replace(/\/$/,'');const target=path.join(dist,route,'test');fs.mkdirSync(target,{recursive:true});fs.writeFileSync(path.join(target,'index.html'),genericTest(item));}
const firstBase=path.join(dist,'algebra','linear-equations-in-one-variable','solving-one-step-linear-equations');for(const [dir,file] of [['problems','one-step-problems.html'],['answers','one-step-answers.html'],['test','one-step-test.html']]){const target=path.join(firstBase,dir);fs.mkdirSync(target,{recursive:true});fs.copyFileSync(path.join(root,file),path.join(target,'index.html'));}
const expl=path.join(firstBase,'explanation','index.html');if(fs.existsSync(expl)){let h=fs.readFileSync(expl,'utf8');if(!h.includes('../test/'))h=h.replace('<a href="../video/english/">English Video<span>Watch in English</span></a>','<a href="../video/english/">English Video<span>Watch in English</span></a><a href="../test/">Lesson Test<span>5 questions · result at the end</span></a>');fs.writeFileSync(expl,h);}
const secondBase=path.join(dist,'algebra','linear-equations-in-one-variable','solving-multi-step-linear-equations');for(const [dir,file] of [['explanation','multi-step-explanation.html'],['problems','multi-step-problems.html'],['answers','multi-step-answers.html'],['test','multi-step-test.html']]){const target=path.join(secondBase,dir);fs.mkdirSync(target,{recursive:true});fs.copyFileSync(path.join(root,file),path.join(target,'index.html'));}
const thirdBase=path.join(dist,'algebra','linear-equations-in-one-variable','variables-on-both-sides');for(const [dir,file] of [['explanation','variables-both-sides-explanation.html'],['problems','variables-both-sides-problems.html'],['answers','variables-both-sides-answers.html'],['test','variables-both-sides-test.html']]){const target=path.join(thirdBase,dir);fs.mkdirSync(target,{recursive:true});fs.copyFileSync(path.join(root,file),path.join(target,'index.html'));}
const fourthBase=path.join(dist,'algebra','linear-equations-in-one-variable','equations-with-fractions');for(const [dir,file] of [['explanation','fractions-explanation.html'],['problems','fractions-problems.html'],['answers','fractions-answers.html'],['test','fractions-test.html']]){const target=path.join(fourthBase,dir);fs.mkdirSync(target,{recursive:true});fs.copyFileSync(path.join(root,file),path.join(target,'index.html'));}
const fifthBase=path.join(dist,'algebra','linear-equations-in-one-variable','equations-with-decimals');for(const [dir,file] of [['explanation','decimals-explanation.html'],['problems','decimals-problems.html'],['answers','decimals-answers.html'],['test','decimals-test.html']]){const target=path.join(fifthBase,dir);fs.mkdirSync(target,{recursive:true});fs.copyFileSync(path.join(root,file),path.join(target,'index.html'));}
const sixthBase=path.join(dist,'algebra','linear-equations-in-one-variable','literal-equations');for(const [dir,file] of [['explanation','literal-equations-explanation.html'],['problems','literal-equations-problems.html'],['answers','literal-equations-answers.html'],['test','literal-equations-test.html']]){const target=path.join(sixthBase,dir);fs.mkdirSync(target,{recursive:true});fs.copyFileSync(path.join(root,file),path.join(target,'index.html'));}
function cairoParts(ms){const d=new Date(ms);const date=new Intl.DateTimeFormat('en-US',{timeZone:'Africa/Cairo',month:'long',day:'numeric',year:'numeric'}).format(d);const time=new Intl.DateTimeFormat('en-US',{timeZone:'Africa/Cairo',hour:'numeric',minute:'2-digit',hour12:true}).format(d);const isoLocal=new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Cairo',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).format(d).replace(', ','T');return{date,time,isoLocal}}
const completed=new Set(['/algebra/linear-equations-in-one-variable/solving-one-step-linear-equations/explanation/','/algebra/linear-equations-in-one-variable/solving-one-step-linear-equations/problems/','/algebra/linear-equations-in-one-variable/solving-one-step-linear-equations/answers/','/algebra/linear-equations-in-one-variable/solving-multi-step-linear-equations/explanation/','/algebra/linear-equations-in-one-variable/solving-multi-step-linear-equations/problems/','/algebra/linear-equations-in-one-variable/solving-multi-step-linear-equations/answers/','/algebra/linear-equations-in-one-variable/variables-on-both-sides/explanation/','/algebra/linear-equations-in-one-variable/variables-on-both-sides/problems/','/algebra/linear-equations-in-one-variable/variables-on-both-sides/answers/','/algebra/linear-equations-in-one-variable/equations-with-fractions/explanation/','/algebra/linear-equations-in-one-variable/equations-with-fractions/problems/','/algebra/linear-equations-in-one-variable/equations-with-fractions/answers/','/algebra/linear-equations-in-one-variable/equations-with-decimals/explanation/','/algebra/linear-equations-in-one-variable/equations-with-decimals/problems/','/algebra/linear-equations-in-one-variable/equations-with-decimals/answers/','/algebra/linear-equations-in-one-variable/literal-equations/explanation/','/algebra/linear-equations-in-one-variable/literal-equations/problems/','/algebra/linear-equations-in-one-variable/literal-equations/answers/']);
const original=JSON.parse(fs.readFileSync(path.join(dist,'schedule.json'),'utf8'));const remaining=original.filter(r=>!completed.has(r.route));const start=Date.UTC(2026,8,3,19,0,0);
for(let i=0;i<remaining.length;i++){const r=remaining[i],p=cairoParts(start+i*12*60*1000);r.index=i+1;r.cairo=`${p.isoLocal}+03:00`;r.timezone='Africa/Cairo';const f=path.join(dist,r.route.replace(/^\//,''),'index.html');if(fs.existsSync(f)){let h=fs.readFileSync(f,'utf8');h=h.replace(/(<small>Scheduled release<\/small><strong>)[^<]*(<\/strong>)/,`$1${p.date}$2`).replace(/(<small>Cairo time \(UTC\+3\)<\/small><strong>)[^<]*(<\/strong>)/,`$1${p.time}$2`);fs.writeFileSync(f,h);}}
fs.writeFileSync(path.join(dist,'schedule.json'),JSON.stringify(remaining,null,2));const q=v=>`"${String(v??'').replace(/"/g,'""')}"`;const csvHeader='index,subject,section,group,lesson,pageType,route,cairo,timezone\n';const csv=csvHeader+remaining.map(r=>[r.index,r.subject,r.section,r.group,r.lesson,r.pageType,r.route,r.cairo,r.timezone].map(q).join(',')).join('\n')+'\n';fs.writeFileSync(path.join(dist,'schedule.csv'),csv);
const first=cairoParts(start),last=cairoParts(start+(remaining.length-1)*12*60*1000);const audit={leafCount:leaves.length,totalLessonRoutes:leaves.length*6,completedContentPages:completed.size,scheduledPages:remaining.length,videoPages:leaves.length*2,testPages:leaves.length,testsScheduled:false,firstRelease:`${first.isoLocal}+03:00 Africa/Cairo`,lastRelease:`${last.isoLocal}+03:00 Africa/Cairo`,routeCollisions:[]};fs.writeFileSync(path.join(dist,'audit.json'),JSON.stringify(audit,null,2));console.log('POSTBUILD',JSON.stringify(audit,null,2));
